# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../pyqt/debuglogwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DebuglogWindow(object):
    def setupUi(self, DebuglogWindow):
        DebuglogWindow.setObjectName("DebuglogWindow")
        DebuglogWindow.resize(959, 474)
        self.tableWidget_log = QtWidgets.QTableWidget(DebuglogWindow)
        self.tableWidget_log.setGeometry(QtCore.QRect(10, 10, 711, 451))
        self.tableWidget_log.setShowGrid(True)
        self.tableWidget_log.setRowCount(0)
        self.tableWidget_log.setColumnCount(4)
        self.tableWidget_log.setObjectName("tableWidget_log")
        self.horizontalLayoutWidget = QtWidgets.QWidget(DebuglogWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(730, 429, 206, 33))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_level = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_level.setObjectName("label_level")
        self.horizontalLayout.addWidget(self.label_level)
        self.comboBox_level = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_level.setObjectName("comboBox_level")
        self.comboBox_level.addItem("")
        self.comboBox_level.addItem("")
        self.comboBox_level.addItem("")
        self.comboBox_level.addItem("")
        self.comboBox_level.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_level)
        self.verticalLayoutWidget = QtWidgets.QWidget(DebuglogWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(730, 10, 211, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_instruments = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_instruments.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_instruments.setObjectName("verticalLayout_instruments")
        self.checkBox_PRESSURE = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_PRESSURE.setChecked(True)
        self.checkBox_PRESSURE.setObjectName("checkBox_PRESSURE")
        self.verticalLayout_instruments.addWidget(self.checkBox_PRESSURE)
        self.checkBox_PUMP = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_PUMP.setChecked(True)
        self.checkBox_PUMP.setObjectName("checkBox_PUMP")
        self.verticalLayout_instruments.addWidget(self.checkBox_PUMP)
        self.checkBox_FLOW_A = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_FLOW_A.setChecked(True)
        self.checkBox_FLOW_A.setObjectName("checkBox_FLOW_A")
        self.verticalLayout_instruments.addWidget(self.checkBox_FLOW_A)
        self.checkBox_FLOW_B = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_FLOW_B.setChecked(True)
        self.checkBox_FLOW_B.setObjectName("checkBox_FLOW_B")
        self.verticalLayout_instruments.addWidget(self.checkBox_FLOW_B)
        self.checkBox_VALVE2x3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_VALVE2x3.setChecked(True)
        self.checkBox_VALVE2x3.setObjectName("checkBox_VALVE2x3")
        self.verticalLayout_instruments.addWidget(self.checkBox_VALVE2x3)
        self.checkBox_E_VALVE1 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_E_VALVE1.setChecked(True)
        self.checkBox_E_VALVE1.setObjectName("checkBox_E_VALVE1")
        self.verticalLayout_instruments.addWidget(self.checkBox_E_VALVE1)
        self.checkBox_E_VALVE2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_E_VALVE2.setChecked(True)
        self.checkBox_E_VALVE2.setObjectName("checkBox_E_VALVE2")
        self.verticalLayout_instruments.addWidget(self.checkBox_E_VALVE2)
        self.checkBox_P_CODE = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_P_CODE.setChecked(True)
        self.checkBox_P_CODE.setObjectName("checkBox_P_CODE")
        self.verticalLayout_instruments.addWidget(self.checkBox_P_CODE)
        self.checkBox_STATE = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_STATE.setChecked(True)
        self.checkBox_STATE.setObjectName("checkBox_STATE")
        self.verticalLayout_instruments.addWidget(self.checkBox_STATE)
        self.checkBox_HUMDEP = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_HUMDEP.setChecked(True)
        self.checkBox_HUMDEP.setObjectName("checkBox_HUMDEP")
        self.verticalLayout_instruments.addWidget(self.checkBox_HUMDEP)
        self.checkBox_HUMGEN = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_HUMGEN.setChecked(True)
        self.checkBox_HUMGEN.setObjectName("checkBox_HUMGEN")
        self.verticalLayout_instruments.addWidget(self.checkBox_HUMGEN)
        self.checkBox_T_SWITCH = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_T_SWITCH.setChecked(True)
        self.checkBox_T_SWITCH.setObjectName("checkBox_T_SWITCH")
        self.verticalLayout_instruments.addWidget(self.checkBox_T_SWITCH)
        self.checkBox_T_SENSOR = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_T_SENSOR.setChecked(True)
        self.checkBox_T_SENSOR.setObjectName("checkBox_T_SENSOR")
        self.verticalLayout_instruments.addWidget(self.checkBox_T_SENSOR)
        self.checkBox_P_SWITCH = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_P_SWITCH.setChecked(True)
        self.checkBox_P_SWITCH.setObjectName("checkBox_P_SWITCH")
        self.verticalLayout_instruments.addWidget(self.checkBox_P_SWITCH)

        self.retranslateUi(DebuglogWindow)
        self.comboBox_level.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DebuglogWindow)

    def retranslateUi(self, DebuglogWindow):
        _translate = QtCore.QCoreApplication.translate
        DebuglogWindow.setWindowTitle(_translate("DebuglogWindow", "Debug Log"))
        self.label_level.setText(_translate("DebuglogWindow", "Min. severity: "))
        self.comboBox_level.setItemText(0, _translate("DebuglogWindow", "DEBUG"))
        self.comboBox_level.setItemText(1, _translate("DebuglogWindow", "INFO"))
        self.comboBox_level.setItemText(2, _translate("DebuglogWindow", "WARNING"))
        self.comboBox_level.setItemText(3, _translate("DebuglogWindow", "ERROR"))
        self.comboBox_level.setItemText(4, _translate("DebuglogWindow", "CRITICAL"))
        self.checkBox_PRESSURE.setText(_translate("DebuglogWindow", "Pressure controller"))
        self.checkBox_PUMP.setText(_translate("DebuglogWindow", "Syringe pump"))
        self.checkBox_FLOW_A.setText(_translate("DebuglogWindow", "Flow A"))
        self.checkBox_FLOW_B.setText(_translate("DebuglogWindow", "Flow B"))
        self.checkBox_VALVE2x3.setText(_translate("DebuglogWindow", "Double 3-way valve"))
        self.checkBox_E_VALVE1.setText(_translate("DebuglogWindow", "Electrovalve 1"))
        self.checkBox_E_VALVE2.setText(_translate("DebuglogWindow", "Electrovalve 2"))
        self.checkBox_P_CODE.setText(_translate("DebuglogWindow", "Picarro Code"))
        self.checkBox_STATE.setText(_translate("DebuglogWindow", "State"))
        self.checkBox_HUMDEP.setText(_translate("DebuglogWindow", "Humdep"))
        self.checkBox_HUMGEN.setText(_translate("DebuglogWindow", "HumGen"))
        self.checkBox_T_SWITCH.setText(_translate("DebuglogWindow", "Temperature Switch"))
        self.checkBox_T_SENSOR.setText(_translate("DebuglogWindow", "Temperature Sensor"))
        self.checkBox_P_SWITCH.setText(_translate("DebuglogWindow", "Pressure Pump Switch"))

