# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../pyqt/redflowmeterwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RedFlowMeterWindow(object):
    def setupUi(self, RedFlowMeterWindow):
        RedFlowMeterWindow.setObjectName("RedFlowMeterWindow")
        RedFlowMeterWindow.resize(577, 387)
        self.groupBox_flowA = QtWidgets.QGroupBox(RedFlowMeterWindow)
        self.groupBox_flowA.setGeometry(QtCore.QRect(0, 10, 571, 181))
        self.groupBox_flowA.setObjectName("groupBox_flowA")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_flowA)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 551, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.flowA_label_flow = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.flowA_label_flow.setObjectName("flowA_label_flow")
        self.gridLayout_2.addWidget(self.flowA_label_flow, 1, 0, 1, 1)
        self.flowA_label_setpoint = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.flowA_label_setpoint.setObjectName("flowA_label_setpoint")
        self.gridLayout_2.addWidget(self.flowA_label_setpoint, 0, 0, 1, 1)
        self.flowA_lineEdit_temperature = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.flowA_lineEdit_temperature.setReadOnly(True)
        self.flowA_lineEdit_temperature.setObjectName("flowA_lineEdit_temperature")
        self.gridLayout_2.addWidget(self.flowA_lineEdit_temperature, 2, 1, 1, 1)
        self.flowA_doubleSpinBox_setpoint = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.flowA_doubleSpinBox_setpoint.setReadOnly(False)
        self.flowA_doubleSpinBox_setpoint.setDecimals(2)
        self.flowA_doubleSpinBox_setpoint.setMaximum(1300.0)
        self.flowA_doubleSpinBox_setpoint.setObjectName("flowA_doubleSpinBox_setpoint")
        self.gridLayout_2.addWidget(self.flowA_doubleSpinBox_setpoint, 0, 1, 1, 1)
        self.flowA_lineEdit_flow = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.flowA_lineEdit_flow.setReadOnly(True)
        self.flowA_lineEdit_flow.setObjectName("flowA_lineEdit_flow")
        self.gridLayout_2.addWidget(self.flowA_lineEdit_flow, 1, 1, 1, 1)
        self.flowA_label_temperature = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.flowA_label_temperature.setObjectName("flowA_label_temperature")
        self.gridLayout_2.addWidget(self.flowA_label_temperature, 2, 0, 1, 1)
        self.flowA_comboBox_control_function = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.flowA_comboBox_control_function.setObjectName("flowA_comboBox_control_function")
        self.gridLayout_2.addWidget(self.flowA_comboBox_control_function, 3, 1, 1, 1)
        self.flowA_label_control_function = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.flowA_label_control_function.setObjectName("flowA_label_control_function")
        self.gridLayout_2.addWidget(self.flowA_label_control_function, 3, 0, 1, 1)
        self.flowA_label_valve_control = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.flowA_label_valve_control.setObjectName("flowA_label_valve_control")
        self.gridLayout_2.addWidget(self.flowA_label_valve_control, 0, 2, 1, 1)
        self.flowA_doubleSpinBox_valve_control = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.flowA_doubleSpinBox_valve_control.setReadOnly(True)
        self.flowA_doubleSpinBox_valve_control.setDecimals(1)
        self.flowA_doubleSpinBox_valve_control.setSingleStep(0.1)
        self.flowA_doubleSpinBox_valve_control.setObjectName("flowA_doubleSpinBox_valve_control")
        self.gridLayout_2.addWidget(self.flowA_doubleSpinBox_valve_control, 0, 3, 1, 1)
        self.flowA_label_alarm = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.flowA_label_alarm.setObjectName("flowA_label_alarm")
        self.gridLayout_2.addWidget(self.flowA_label_alarm, 1, 2, 1, 1)
        self.flowA_lineEdit_alarm = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.flowA_lineEdit_alarm.setReadOnly(True)
        self.flowA_lineEdit_alarm.setObjectName("flowA_lineEdit_alarm")
        self.gridLayout_2.addWidget(self.flowA_lineEdit_alarm, 1, 3, 1, 1)
        self.flowA_label_harware_error = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.flowA_label_harware_error.setObjectName("flowA_label_harware_error")
        self.gridLayout_2.addWidget(self.flowA_label_harware_error, 2, 2, 1, 1)
        self.flowA_toolButton_soft_reset = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.flowA_toolButton_soft_reset.setObjectName("flowA_toolButton_soft_reset")
        self.gridLayout_2.addWidget(self.flowA_toolButton_soft_reset, 3, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.flowA_lineEdit_hardware_error = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.flowA_lineEdit_hardware_error.setReadOnly(True)
        self.flowA_lineEdit_hardware_error.setObjectName("flowA_lineEdit_hardware_error")
        self.horizontalLayout_2.addWidget(self.flowA_lineEdit_hardware_error)
        self.flowA_toolButton_reset_hardware_error = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.flowA_toolButton_reset_hardware_error.setObjectName("flowA_toolButton_reset_hardware_error")
        self.horizontalLayout_2.addWidget(self.flowA_toolButton_reset_hardware_error)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 3, 1, 1)
        self.groupBox_flowB = QtWidgets.QGroupBox(RedFlowMeterWindow)
        self.groupBox_flowB.setGeometry(QtCore.QRect(0, 200, 571, 181))
        self.groupBox_flowB.setObjectName("groupBox_flowB")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_flowB)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 551, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.flowB_label_setpoint = QtWidgets.QLabel(self.gridLayoutWidget)
        self.flowB_label_setpoint.setObjectName("flowB_label_setpoint")
        self.gridLayout.addWidget(self.flowB_label_setpoint, 0, 0, 1, 1)
        self.flowB_lineEdit_temperature = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.flowB_lineEdit_temperature.setReadOnly(True)
        self.flowB_lineEdit_temperature.setObjectName("flowB_lineEdit_temperature")
        self.gridLayout.addWidget(self.flowB_lineEdit_temperature, 2, 1, 1, 1)
        self.flowB_label_flow = QtWidgets.QLabel(self.gridLayoutWidget)
        self.flowB_label_flow.setObjectName("flowB_label_flow")
        self.gridLayout.addWidget(self.flowB_label_flow, 1, 0, 1, 1)
        self.flowB_lineEdit_flow = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.flowB_lineEdit_flow.setReadOnly(True)
        self.flowB_lineEdit_flow.setObjectName("flowB_lineEdit_flow")
        self.gridLayout.addWidget(self.flowB_lineEdit_flow, 1, 1, 1, 1)
        self.flowB_doubleSpinBox_setpoint = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.flowB_doubleSpinBox_setpoint.setReadOnly(False)
        self.flowB_doubleSpinBox_setpoint.setDecimals(2)
        self.flowB_doubleSpinBox_setpoint.setMaximum(1300.0)
        self.flowB_doubleSpinBox_setpoint.setSingleStep(1.0)
        self.flowB_doubleSpinBox_setpoint.setObjectName("flowB_doubleSpinBox_setpoint")
        self.gridLayout.addWidget(self.flowB_doubleSpinBox_setpoint, 0, 1, 1, 1)
        self.flowB_comboBox_control_function = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.flowB_comboBox_control_function.setObjectName("flowB_comboBox_control_function")
        self.gridLayout.addWidget(self.flowB_comboBox_control_function, 3, 1, 1, 1)
        self.flowB_label_temperature = QtWidgets.QLabel(self.gridLayoutWidget)
        self.flowB_label_temperature.setObjectName("flowB_label_temperature")
        self.gridLayout.addWidget(self.flowB_label_temperature, 2, 0, 1, 1)
        self.flowB_label_control_function = QtWidgets.QLabel(self.gridLayoutWidget)
        self.flowB_label_control_function.setObjectName("flowB_label_control_function")
        self.gridLayout.addWidget(self.flowB_label_control_function, 3, 0, 1, 1)
        self.flowB_label_valve_control = QtWidgets.QLabel(self.gridLayoutWidget)
        self.flowB_label_valve_control.setObjectName("flowB_label_valve_control")
        self.gridLayout.addWidget(self.flowB_label_valve_control, 0, 2, 1, 1)
        self.flowB_doubleSpinBox_valve_control = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.flowB_doubleSpinBox_valve_control.setReadOnly(True)
        self.flowB_doubleSpinBox_valve_control.setDecimals(1)
        self.flowB_doubleSpinBox_valve_control.setSingleStep(0.1)
        self.flowB_doubleSpinBox_valve_control.setObjectName("flowB_doubleSpinBox_valve_control")
        self.gridLayout.addWidget(self.flowB_doubleSpinBox_valve_control, 0, 3, 1, 1)
        self.flowB_lineEdit_alarm = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.flowB_lineEdit_alarm.setReadOnly(True)
        self.flowB_lineEdit_alarm.setObjectName("flowB_lineEdit_alarm")
        self.gridLayout.addWidget(self.flowB_lineEdit_alarm, 1, 3, 1, 1)
        self.flowB_label_alarm = QtWidgets.QLabel(self.gridLayoutWidget)
        self.flowB_label_alarm.setObjectName("flowB_label_alarm")
        self.gridLayout.addWidget(self.flowB_label_alarm, 1, 2, 1, 1)
        self.flowB_label_harware_error = QtWidgets.QLabel(self.gridLayoutWidget)
        self.flowB_label_harware_error.setObjectName("flowB_label_harware_error")
        self.gridLayout.addWidget(self.flowB_label_harware_error, 2, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.flowB_lineEdit_hardware_error = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.flowB_lineEdit_hardware_error.setReadOnly(True)
        self.flowB_lineEdit_hardware_error.setObjectName("flowB_lineEdit_hardware_error")
        self.horizontalLayout.addWidget(self.flowB_lineEdit_hardware_error)
        self.flowB_toolButton_reset_hardware_error = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.flowB_toolButton_reset_hardware_error.setObjectName("flowB_toolButton_reset_hardware_error")
        self.horizontalLayout.addWidget(self.flowB_toolButton_reset_hardware_error)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 3, 1, 1)
        self.flowB_toolButton_soft_reset = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.flowB_toolButton_soft_reset.setObjectName("flowB_toolButton_soft_reset")
        self.gridLayout.addWidget(self.flowB_toolButton_soft_reset, 3, 3, 1, 1)
        self.action_pump = QtWidgets.QAction(RedFlowMeterWindow)
        self.action_pump.setObjectName("action_pump")
        self.action_flows = QtWidgets.QAction(RedFlowMeterWindow)
        self.action_flows.setObjectName("action_flows")
        self.action_pressure = QtWidgets.QAction(RedFlowMeterWindow)
        self.action_pressure.setObjectName("action_pressure")
        self.action_valve2x3 = QtWidgets.QAction(RedFlowMeterWindow)
        self.action_valve2x3.setObjectName("action_valve2x3")
        self.action_electrovalves = QtWidgets.QAction(RedFlowMeterWindow)
        self.action_electrovalves.setObjectName("action_electrovalves")
        self.groupBox_flowA.raise_()
        self.groupBox_flowB.raise_()
        self.flowB_label_setpoint.raise_()

        self.retranslateUi(RedFlowMeterWindow)
        QtCore.QMetaObject.connectSlotsByName(RedFlowMeterWindow)

    def retranslateUi(self, RedFlowMeterWindow):
        _translate = QtCore.QCoreApplication.translate
        RedFlowMeterWindow.setWindowTitle(_translate("RedFlowMeterWindow", "Flow Controller"))
        self.groupBox_flowA.setTitle(_translate("RedFlowMeterWindow", "Flow Controller A"))
        self.flowA_label_flow.setText(_translate("RedFlowMeterWindow", "Flow (mln/min):"))
        self.flowA_label_setpoint.setText(_translate("RedFlowMeterWindow", "Setpoint (mln/min):"))
        self.flowA_label_temperature.setText(_translate("RedFlowMeterWindow", "Temperature (°C):"))
        self.flowA_comboBox_control_function.setToolTip(_translate("RedFlowMeterWindow", "<html><head/><body><p>This widget is write only: it will not be modified if the control function is modified elsewhere.</p></body></html>"))
        self.flowA_label_control_function.setText(_translate("RedFlowMeterWindow", "Ctrl Function"))
        self.flowA_label_valve_control.setText(_translate("RedFlowMeterWindow", "Valve ctrl (%):"))
        self.flowA_label_alarm.setText(_translate("RedFlowMeterWindow", "Alarm:"))
        self.flowA_label_harware_error.setText(_translate("RedFlowMeterWindow", "Hardware errors:"))
        self.flowA_toolButton_soft_reset.setText(_translate("RedFlowMeterWindow", "Reset Flow Controller"))
        self.flowA_toolButton_reset_hardware_error.setText(_translate("RedFlowMeterWindow", "Reset"))
        self.groupBox_flowB.setTitle(_translate("RedFlowMeterWindow", "Flow Controller B"))
        self.flowB_label_setpoint.setText(_translate("RedFlowMeterWindow", "Setpoint (mln/min):"))
        self.flowB_label_flow.setText(_translate("RedFlowMeterWindow", "Flow (mln/min):"))
        self.flowB_comboBox_control_function.setToolTip(_translate("RedFlowMeterWindow", "<html><head/><body><p>This widget is write only: it will not be modified if the control function is modified elsewhere.</p></body></html>"))
        self.flowB_label_temperature.setText(_translate("RedFlowMeterWindow", "Temperature (°C):"))
        self.flowB_label_control_function.setText(_translate("RedFlowMeterWindow", "Ctrl Function"))
        self.flowB_label_valve_control.setText(_translate("RedFlowMeterWindow", "Valve ctrl (%):"))
        self.flowB_label_alarm.setText(_translate("RedFlowMeterWindow", "Alarm:"))
        self.flowB_label_harware_error.setText(_translate("RedFlowMeterWindow", "Hardware errors:"))
        self.flowB_toolButton_reset_hardware_error.setText(_translate("RedFlowMeterWindow", "Reset"))
        self.flowB_toolButton_soft_reset.setText(_translate("RedFlowMeterWindow", "Reset Flow Controller"))
        self.action_pump.setText(_translate("RedFlowMeterWindow", "Syringe pump"))
        self.action_flows.setText(_translate("RedFlowMeterWindow", "Flow controllers"))
        self.action_pressure.setText(_translate("RedFlowMeterWindow", "Pressure controller"))
        self.action_valve2x3.setText(_translate("RedFlowMeterWindow", "Double 3-ways valve"))
        self.action_electrovalves.setText(_translate("RedFlowMeterWindow", "Electro-valves"))

